version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_volume:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    container_name: hice_db


  backend_1:
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 80"
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
    env_file:
      - ./.env
    container_name: hice_backend_1

  backend_2:
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 81"
    restart: always
    ports:
      - "81:81"
    depends_on:
      - backend_1
    env_file:
      - ./.env
    container_name: hice_backend_2

volumes:
  db_volume:
