"""empty message

Revision ID: 64aefe27d1ae
Revises:
Create Date: 2023-06-02 13:37:16.136674

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '64aefe27d1ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'message',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('text', sa.Text(), nullable=True),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('create_date', sa.DateTime(), nullable=False),
        sa.Column('message_counter', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('message_counter', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('message')
    # ### end Alembic commands ###
